# Generated by Django 3.2 on 2022-08-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrame',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='macrame',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
