# Generated by Django 3.2 on 2022-08-27 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('macrames', '0002_auto_20220819_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrame',
            name='likes',
            field=models.ManyToManyField(null=True, related_query_name='mac_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
