# Generated by Django 3.2 on 2022-08-27 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('macrames', '0003_macrame_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrame',
            name='likes',
            field=models.ManyToManyField(blank=True, related_query_name='mac_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
